[colors.primary]
background = "#ffffff"
foreground = "#112b37"

[colors.normal]
black = "#000000"
red = "#d20602"
green = "#5ea520"
yellow = "#c39101"
blue = "#2e4fb5"
magenta = "#a91acc"
cyan = "#067a82"
white = "#dddddd"

[colors.bright]
black = "#767676"
red = "#f2201f"
green = "#23fd00"
yellow = "#fffd00"
blue = "#1a8fff"
magenta = "#fd28ff"
cyan = "#14ffff"
white = "#ffffff"

[colors.selection]
text = "CellForeground"
background = "#d2d9d9"

