[colors.primary]
background  =   "#0f111a"
foreground  =   "#D8DEE9"

[colors.cursor]
cursor  =   "#ff4151"

[colors.normal]
black   =   "#4C566A"
red     =   "#BF616A"
green   =   "#A3BE8C"
yellow  =   "#EBCB8B"
blue    =   "#81A1C1"
magenta =   "#B48EAD"
cyan    =   "#88C0D0"
white   =   "#E5E9F0"

